### ISSUE TITLE
Activation not from main site main network

### ISSUE THREAD

**Issue by MaximeCulea** [stuttter/wp-blog-meta#4]
Hi,
As the plugin is not activated from the main site and main network since WP 4.3.0, nothing happens.
This is due to `wp_should_upgrade_global_tables` check from https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/upgrade.php#L2202 which does the next thing : https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/upgrade.php#L2905.

I don't know which can be the best way to resolve this, but maybe not displaying the plugin on other networks, or displaying an error message on admin could be possible ?

I suggest in first place to update the readme to informe people about this :)

Best,

**Comment by johnjamesjacoby** [comment]
Thanks for noticing this @MaximeCulea.

A PR to the readme would be awesome.

**Comment by MaximeCulea** [comment]
No problem @johnjamesjacoby !
Here we are : https://github.com/stuttter/wp-blog-meta/pull/5
